# -*- coding: utf-8 -*-
"""Throwaway: name the still-unknown field hashes by brute-forcing candidate
strings through the DEK hash and matching the observed hash set."""
import os, io, sys, itertools
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
# Anchored to this file rather than to the caller's directory: these were
# written to be run from the folder they lived in, and that folder has moved.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', 'src'))
import paths

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', 'src', 'tl2'))   # dat_hash lives in src/tl2 now
from dat_hash import dek

UNK = {
    0xEDD3AA06: 'str, ~19-digit signed id',
    0x46811078: 'int, const 100',
    0x87425B52: 'int, 100/80/90',
    0xB0A39AF9: 'int, 100/40',
    0x0A7618F3: 'str MALE/FEMALE',
    0x00679E28: 'str .mesh wardrobe',
    0x85142829: 'int 40/0',
    0x8FAB5E28: 'str .png wardrobe',
    0x89AD5F5F: 'int 40/0',
    0x61F25E7E: 'int 40/0',
    0x4B4A411C: 'int 50/40/34',
    0x0569A08F: 'int 70/25/40',
    0xDB0FCFA6: 'int 40',
    0x7F8FD5DE: 'int 25/40/50/34',
    0x9D681E79: 'int 16/33',
    0xCA5E6F5D: 'int 50/20/34/60',
    0xA670656D: 'int 100/115/140/160',
    0xB9F80B70: 'str "Unidentified X"',
    0x00680C25: 'str HUMAN',
    0x0F108DC5: 'f32 1.5',
    0xF7319FCA: 'str particle layout',
    0x0C36E3FE: 'int 160/107',
    0x8C36E3BB: 'int 160/214',
    0x0F01B0A5: 'f32 0.8/1/9/0.6',
    0xE4D77B3B: 'f32 120/0/60',
    0xE720656C: 'int 200',
    0x5F21EB87: 'f32 50/0/25',
    0x0E3B167F: 'str EQUIPMENT',
    0x4BC760FF: 'f32 1.6/1.1',
    0x035865DF: 'str icon_weapon_polearm01',
    0xBB365EF7: 'str "Item Fall"',
    0xFB341ECD: 'str AxeGet',
    0xBB371EE5: 'str AxeDrop',
    0x13CCD6CD: 'str SwordFlesh',
    0x9ACC1E8E: 'str SwordSwing',
    0x35D69ECD: 'f32 1.2/0.8',
    0xAC3B35A9: 'str fist16L',
    0xFA167E0F: 'int 392914174',
    0xE0683EAD: 'str <ref>',
    0xE81B4C1C: 'str TRANSFER',
    0x006B6E45: 'str INTERRUPT',
    0x0000C4F4: 'str GRELLS/ENGINEER_B15',
}

VOCAB = """DAMAGE ATTACK SPEED ARMOR HEALTH MANA LEVEL REQUIRED REQUIREMENT CHANCE
RANGE DURATION SOUND EFFECT PARTICLE PARTICLEFILE TEXTURE MESH MESHFILE WARDROBE
ICON SCALE TYPE NAME SLOT SIZE OFFSET RADIUS HEIGHT WIDTH ANGLE WEIGHT VALUE COST
GOLD RARITY PERCENT BONUS MIN MAX ITEM UNIT MONSTER PLAYER WEAPON SHIELD CHEST
HELMET BOOTS GLOVES BELT RING NECKLACE BASE MAGIC NORMAL UNIQUE LEGENDARY RARE
RANDOM DROP GET IMPACT SWING FALL PICKUP EQUIP BREAK OPEN DEATH HIT CAST SKILL
SPELL AFFIX AFFIXES STAT STATS ATTRIBUTE PHYSICAL ICE FIRE ELECTRIC POISON
CRITICAL CRIT STUN KNOCKBACK BLEED BURN FREEZE SHOCK SLOW HASTE LUCK FIND
MAGIC_FIND BLOCK DODGE PARRY RESIST RESISTANCE ABSORB LIFESTEAL MANASTEAL REGEN
RECHARGE COOLDOWN CHARGE PURCHASE SELL PRICE STACK COUNT NUMBER
GENDER SEX RACE SPECIES CLASS CHARACTER BODY HEAD HAND FOOT FEET FINGER NECK
BACK SHOULDER LEGS PELVIS TORSO TAIL WING HORN EYE EAR MOUTH
EMPTY NONE DEFAULT BLANK IDENTIFIED UNIDENTIFIED UNKNOWN MYSTERIOUS MYSTERY
DISPLAY DISPLAYNAME DESCRIPTION DESC TEXT MATERIALFILE MODELFILE SKELETON
BONE BONES ATTACH ATTACHMENT ATTACHPOINT SOCKET SOCKETS
WORLD SCENE ZONE LAYOUT TEMPLATE DUNGEON FLAGS FLAG MASK BITS INDEX ORDER
PRIORITY PROBABILITY TIMER TIME DELAY INTERVAL FREQUENCY AMOUNT TOTAL CURRENT
MODIFIER MOD PREFIX SUFFIX TIER SET SETS COLLECTION COLLECTIONNAME SETNAME
STASH STORAGE INVENTORY MERCHANT VENDOR SHOP
VITALITY FOCUS DEFENSE DEXTERITY STRENGTH MOVEMENT MOVESPEED TURNSPEED
TARGET TARGETS ENEMY ENEMIES FRIEND ALLY ALLIES SELF WORTH MULTIPLIER
LIGHT AMBIENT DIFFUSE EMISSIVE GLOW USEABLE USABLE CONSUMABLE STACKABLE
ITEMLEVEL ILVL LEVELREQ FLESH WOOD METAL STONE MATERIAL SOUNDMATERIAL
ANIMATION ANIM ANIMSET FILE SETTING USE TYPE2 MATERIAL_TYPE
"""

words = sorted({w for w in VOCAB.split() if w})
cand = set(words)
for a, b in itertools.product(words, words):
    cand.add(a + '_' + b)

cand |= {
    'VITALITY_REQUIRED', 'FOCUS_REQUIRED', 'ITEM_LEVEL', 'ATTACK_SPEED',
    'MIN_SPEED', 'MAX_SPEED', 'UNIDENTIFIED_NAME', 'UNIDENTIFIEDNAME',
    'UNKNOWN_NAME', 'UNKNOWNNAME', 'IDENTIFY_NAME', 'MYSTERY_NAME',
    'UNID_NAME', 'UNIDNAME', 'DISPLAY_NAME', 'WARDROBE_MESH',
    'PARTICLE_FILE', 'PARTICLES', 'PARTICLE_LAYOUT', 'LAYOUT_FILE',
    'EQUIP_SLOT', 'EQUIPMENT_SLOT', 'ITEM_SLOT', 'INVENTORY_SLOT',
    'GET_SOUND', 'DROP_SOUND', 'IMPACT_SOUND', 'SWING_SOUND', 'FALL_SOUND',
    'ITEMFALL', 'ITEM_FALL', 'PICKUP_SOUND', 'ATTACH_POINT', 'ATTACHMENT',
    'MODEL_SCALE', 'MESH_SCALE', 'UNIFORM_SCALE', 'RANDOM_NAME', 'BASE_NAME',
    'UNIQUE_ID', 'ITEM_ID', 'GUID', 'UID', 'ID', 'RANDOM_SEED', 'SEED',
    'VARIANT', 'VARIATION', 'AFFIX_HASH', 'SPELL_HASH', 'DROP_CHANCE',
    'SPAWN_CHANCE', 'SPAWNCHANCE', 'DROP_RATE', 'DROPRATE',
    'NORMAL_CHANCE', 'MAGIC_CHANCE', 'UNIQUE_CHANCE', 'LEGENDARY_CHANCE',
    'MIN_COUNT', 'MAX_COUNT', 'MIN_AMOUNT', 'MAX_AMOUNT', 'MIN_STACK',
    'MAX_STACK', 'MIN_DAMAGE', 'MAX_DAMAGE', 'MIN_ARMOR', 'MAX_ARMOR',
    'SOUND_MATERIAL', 'SOUND_TYPE', 'SOUND_SET', 'SOUNDSET',
    'ANIM_SET', 'ANIMATION_SET', 'ANIMATION_FILE', 'ANIMFILE',
    'AIM_OFFSET', 'AIM_HEIGHT', 'AIMHEIGHT', 'TARGET_OFFSET',
    'TARGET_OFFSET_X', 'TARGETOFFSETX', 'TARGETOFFSETY', 'TARGETOFFSETZ',
    'OFFSET_X', 'OFFSET_Y', 'OFFSET_Z', 'BOUNDING_RADIUS',
    'COLLISION_RADIUS', 'DEPTH', 'CAMERA_OFFSET', 'CAMERA_HEIGHT',
    'CAMERA_DISTANCE', 'TURN_RATE', 'MOVE_SPEED', 'RUN_SPEED', 'WALK_SPEED',
    'LEVEL_REQUIRED', 'REQUIRED_LEVEL', 'LEVELREQUIRED', 'PURCHASE_PRICE',
    'SELL_PRICE', 'GOLD_VALUE', 'SORT_ORDER', 'SORTORDER',
    'IS_UNIQUE', 'ALWAYS_DROP', 'NO_DROP', 'UNDROPPABLE',
    'USE_TYPE', 'USE', 'MATERIAL_TYPE', 'SPECIAL', 'SPAWN',
    'SPAWNCLASS', 'SPAWN_CLASS', 'UNITTHEME', 'UNITTYPE_NAME',
    'ONHIT', 'ON_HIT', 'ONKILL', 'ON_KILL', 'TRIGGER', 'TRIGGERS',
    'MINLEVEL_REQUIRED', 'MAXLEVEL_REQUIRED', 'RARITY_NAME', 'TIER_NAME',
    'COLOR', 'COLOUR', 'TINT', 'GLOW_COLOR', 'PARTICLE_COLOR',
    'EMISSIVE_COLOR', 'DIFFUSE_COLOR', 'AMBIENT_COLOR',
}

print('candidates:', len(cand))
found = {}
for s in cand:
    h = dek(s)
    if h in UNK:
        found.setdefault(h, []).append(s)

named = 0
for h in sorted(UNK):
    if h in found:
        print('  0x%08X = %-24s  (%s)' % (h, ' | '.join(sorted(found[h])), UNK[h]))
        named += 1
    else:
        print('  0x%08X = %-24s  (%s)' % (h, '???', UNK[h]))
print()
print('named %d of %d' % (named, len(UNK)))
